version: "3.8"

services:
  app:
    build: ./app
    container_name: app
    ports:
      - "3000:3000"
    networks: [monitoring]
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks: [monitoring]
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml:ro
    ports:
      - "9090:9090"
    networks: [monitoring]
    depends_on:
      - app
      - node-exporter
      - alertmanager
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3001:3000"
    networks: [monitoring]
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  monitoring: {}

volumes:
  grafana-data: {}