global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: "nodeapp"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:3000"]

  - job_name: "node-exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["node-exporter:9100"]
